#ifndef MANUALCONTROLSETTINGS_H
#define MANUALCONTROLSETTINGS_H
#include "common.h"
    enum ChannelGroups
    {
      MANUALCONTROLSETTINGS_CHANNELGROUPS_THROTTLE, 
      MANUALCONTROLSETTINGS_CHANNELGROUPS_ROLL,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_PITCH,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_YAW,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_FLIGHTMODE,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_COLLECTIVE,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY0,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY1,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY2,  
      MANUALCONTROLSETTINGS_CHANNELGROUPS_ARMING,
      MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM 
    };
struct ManualControlSettingsData
{
    uint8 RssiChannelNumber[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 RssiMax[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 RssiMin[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 RssiPwmPeriod[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    uint8 ChannelNumber[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 ChannelMin[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 ChannelNeutral[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    int16 ChannelMax[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    float Deadband[MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM];
    uint16 Arming;
    //enum Stabilization1Settings[3];
    enum Stabilization1Settings
    {
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_NONE,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_RATE,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_ATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_AXISLOCK,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_WEAKLEVELING,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_VIRTUALBAR,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_HORIZON,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_RELAYRATE,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_RELAYATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_POI,
        MANUALCONTROLSETTINGS_STABILIZATION1SETTINGS_COORDINATEDFLIGHT
    }Stabilization1Settings[3];
   // enum Stabilization2Settings[3];
    enum Stabilization2Settings
    {
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_NONE,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_RATE,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_ATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_AXISLOCK,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_WEAKLEVELING,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_VIRTUALBAR,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_HORIZON,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_RELAYRATE,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_RELAYATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_POI,
        MANUALCONTROLSETTINGS_STABILIZATION2SETTINGS_COORDINATEDFLIGHT
    }Stabilization2Settings[3];
   // enum Stabilization3Settings[3];
    enum Stabilization3Settings
    {
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_NONE,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_RATE,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_ATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_AXISLOCK,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_WEAKLEVELING,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_VIRTUALBAR,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_HORIZON,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_RELAYRATE,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_RELAYATTITUDE,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_POI,
        MANUALCONTROLSETTINGS_STABILIZATION3SETTINGS_COORDINATEDFLIGHT
    }Stabilization3Settings[3];
    uint8 FlightModeNumber;
    enum FlightModePosition
    {
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_MANUAL,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_STABILIZED1,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_STABILIZED2,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_STABILIZED3,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_AUTOTUNE,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_ALTITUDEHOLD,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_VELOCITYCONTROL,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_POSITIONHOLD,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_RETURNTOHOME,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_PATHPLANNER,
        MANUALCONTROLSETTINGS_FLIGHTMODEPOSITION_TABLETCONTROL
    }FlightModePosition;
    uint16 ArmedTimeout;
};
typedef struct ManualControlSettingsData ManualControlSettingsData;
#endif // MANUALCONTROLSETTINGS_H
