#ifndef MOTORSETTINGS_H
#define MOTORSETTINGS_H
#include <core_common.h>
enum 
{
  MOTORSETTINGS_EDP_L,
  MOTORSETTINGS_EDP_H,
  MOTORSETTINGS_STP,
  MOTORSETTINGS_FREQ,
  MOTORSETTINGS_NUMELEM
};
enum 
{
  MOTORSETTINGS_CH_1,
  MOTORSETTINGS_CH_2,
  MOTORSETTINGS_CH_3,
  MOTORSETTINGS_CH_4,
  MOTORSETTINGS_CH_NUMELEM
};
struct MotorSettingsData
{
uint16 Motor[MOTORSETTINGS_CH_NUMELEM][MOTORSETTINGS_NUMELEM];
//uint16 Motor2[MOTORSETTINGS_NUMELEM];
//uint16 Motor3[MOTORSETTINGS_NUMELEM];
//uint16 Motor4[MOTORSETTINGS_NUMELEM];
};
typedef struct MotorSettingsData MotorSettingsData;
#endif // MOTORSETTINGS_H
