#ifndef SYSTEMSETTINGS_H
#define SYSTEMSETTINGS_H
#include "common.h"
struct SystemSettingsData
{
    enum AirframeType
    {
        SYSTEMSETTINGS_AIRFRAMETYPE_FIXEDWING,
        SYSTEMSETTINGS_AIRFRAMETYPE_FIXEDWINGELEVON,
        SYSTEMSETTINGS_AIRFRAMETYPE_FIXEDWINGVTAIL,
        SYSTEMSETTINGS_AIRFRAMETYPE_VTOL,
        SYSTEMSETTINGS_AIRFRAMETYPE_HELICP,
        SYSTEMSETTINGS_AIRFRAMETYPE_QUADX,
        SYSTEMSETTINGS_AIRFRAMETYPE_QUADP,
        SYSTEMSETTINGS_AIRFRAMETYPE_HEXA,
        SYSTEMSETTINGS_AIRFRAMETYPE_OCTO,
        SYSTEMSETTINGS_AIRFRAMETYPE_CUSTOM,
        SYSTEMSETTINGS_AIRFRAMETYPE_HEXAX,
        SYSTEMSETTINGS_AIRFRAMETYPE_OCTOV,
        SYSTEMSETTINGS_AIRFRAMETYPE_OCTOCOAXP,
        SYSTEMSETTINGS_AIRFRAMETYPE_OCTOCOAXX,
        SYSTEMSETTINGS_AIRFRAMETYPE_HEXACOAX,
        SYSTEMSETTINGS_AIRFRAMETYPE_TRI,
        SYSTEMSETTINGS_AIRFRAMETYPE_GROUNDVEHICLECAR,
        SYSTEMSETTINGS_AIRFRAMETYPE_GROUNDVEHICLEDIFFERENTIAL,
        SYSTEMSETTINGS_AIRFRAMETYPE_GROUNDVEHICLEMOTORCYCLE
    }AirframeType;
    uint32 AirframeCategorySpecificConfiguration;
};
typedef struct SystemSettingsData SystemSettingsData;
#endif // SYSTEMSETTINGS_H
